// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeatherAlertsBot.DAL.Context;

#nullable disable

namespace WeatherAlertsBot.DAL.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20230105210641_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WeatherAlertsBot.DAL.Entities.Command", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("SubsrciberChatId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubsrciberChatId");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("WeatherAlertsBot.DAL.Entities.Subsrciber", b =>
                {
                    b.Property<long>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.HasKey("ChatId");

                    b.ToTable("Subsrcibers");
                });

            modelBuilder.Entity("WeatherAlertsBot.DAL.Entities.Command", b =>
                {
                    b.HasOne("WeatherAlertsBot.DAL.Entities.Subsrciber", "Subsrciber")
                        .WithMany("Commands")
                        .HasForeignKey("SubsrciberChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subsrciber");
                });

            modelBuilder.Entity("WeatherAlertsBot.DAL.Entities.Subsrciber", b =>
                {
                    b.Navigation("Commands");
                });
#pragma warning restore 612, 618
        }
    }
}
