version: '3.8'

services:
 weatheralertsbot:
  image: shindqq/weatheralertsbot_image
  restart: unless-stopped
  container_name: weatheralertsbot_compose_container
  volumes:
  - ./appsettings.json:src/WeatherAlertsBot/appsetting.json
  build:
   context: .
   dockerfile: WeatherAlertsBot/Dockerfile
  ports:
  - "2001:443" 
  - "2000:80" 
 mysql:
  image: mysql
  restart: unless-stopped
  container_name: mysql_bot_compose-server
  environment:
   MYSQL_DATABASE: 'WeatherAlertsBotDb'
   MYSQL_USER: 'Shind'
   MYSQL_PASSWORD: 'VaUMdqnW2TwkZJ34ZxkXNHepWIq3kAHKxvYCxNygPZRVHcIrBy2bMxIzth'
   MYSQL_ROOT_PASSWORD: 'VaUMdqnW2TwkZJ34ZxkXNHepWIq3kAHKxvYCxNygPZRVHcIrBy2bMxIzth'
  ports:
   - '3307:3306'
  expose:
   - '3306'
  volumes:
  - weatheralertsbotdb:/var/lib/mysql

volumes:
  appsettings.json:
   external: true
  weatheralertsbotdb: